name: Security Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  docker-build-and-sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t juice-shop:latest .

      - name: Install Syft
        uses: anchore/syft-action@v0.19.0
        with:
          version: v1.17.0

      - name: Generate SBOM with Syft
        run: |
          syft packages docker:juice-shop:latest -o json > sbom.json
          syft packages docker:juice-shop:latest -o spdx-json > sbom.spdx.json
          syft packages docker:juice-shop:latest -o table

      - name: Upload SBOM artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sbom-files
          path: |
            sbom.json
            sbom.spdx.json
