name: Guvenlik Kontrolu

# Bu workflow ne zaman çalışsın?
# Hem push yapıldığında hem de Pull Request açıldığında çalışsın.
on:
  push:
  pull_request:

jobs:
  # İşin adı (Status Check kısmında bu isim görünecek)
  basit-tarama:
    runs-on: ubuntu-latest  # GitHub'ın sağladığı sanal Ubuntu makinesinde çalış
    steps:
      
      # 1. Adım: Tarama başlangıç çıktısı
      - name: Ekrana Mesaj Yaz
        run: echo "Güvenlik Taraması Başlıyor"

      # 2. Adım: Kodları makineye çek (Checkout)
      # SHA Hash ile sabitleme (Pinning) yapıldı!
      - name: Kodlari Cek (Checkout)
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
