name: Guvenlik Kontrolu

# Bu workflow ne zaman çalışsın?
# Hem push yapıldığında hem de Pull Request açıldığında çalışsın.
on:
  push:
  pull_request:

jobs:
  # İşin adı (Status Check kısmında bu isim görünecek)
  basit-tarama:
    runs-on: ubuntu-latest # GitHub'ın sağladığı sanal Ubuntu makinesinde çalış
    steps:
      # 1. Adım: Tarama başlangıç çıktısı
      - name: Ekrana Mesaj Yaz
        run: echo "Güvenlik Taraması Başlıyor"

      # 2. Adım: Kodları makineye çek (Checkout)
      # SHA Hash ile sabitleme (Pinning) yapıldı!
      - name: Kodlari Cek (Checkout)
        uses: actions/checkout@v1 # v4.2.2
          with:
          fetch-depth: 0  # <--- BU SATIRI EKLİYORUZ (Tüm Git geçmişini indirir)

        # 3. Adım: Kodları Static Analysis ile Tara
      - name: Semgrep Security Scan
        # returntocorp/semgrep-action@v1 kullanıyoruz
        # Semgrep uygulamamizin kodlarinin "Bizim yazdigimiz Kodlar" kismini taramasini saglar hazir bilesikleri ve kutuphaneleri taramaz
        uses: returntocorp/semgrep-action@v1 # versiyon tag kullandik
        with:
          # Görev: Sadece Javascript ve Typescript tara
          # Görev: "High" bulgularda fail et
          # Not: Semgrep Action varsayılan olarak bulgu bulduğunda hata verir (auditOn: push)
          # Ancak özellikle sadece hatalarda durmasını garantiye almak için açıklama ekliyoruz.
          config: >-
            p/javascript
            p/typescript
        continue-on-error: true # Hata olsa bile devam et demek.

      # 4. Adım: SCA ve Bağımlılık Taraması (Çarşamba Görevi)
      # Güvenlik Açığı Taraması için Trivy Kullanımı (Hazir paketlerin güvenlik açıklarını bulmak içindir)
      - name: Trivy Vulnerability Scanner
        # aquasecurity/trivy-action kullanıyoruz
        uses: aquasecurity/trivy-action@18f2510ee396bbf400402947b394f2dd8c87dbb0 # v0.29.0 (Sabitlendi!)
        with:
          scan-type: "fs" # Dosya sistemini tara
          scan-ref: "." # Mevcut dizini tara
          format: "table" # Sonucu tablo olarak göster
          #exit-code: '1'            # Hata bulursan pipeline'ı durdur (Fail)
          severity: "CRITICAL,HIGH" # Sadece Kritik ve Yüksek seviyeleri önemse

      # 5. Adım: SBOM (Yazılım Malzeme Listesi) Oluşturma. Listeyi bize tablo olarak verecektir.
      - name: Generate SBOM
        uses: aquasecurity/trivy-action@18f2510ee396bbf400402947b394f2dd8c87dbb0 # v0.29.0
        with:
          scan-type: "fs"
          format: "cyclonedx" # Endüstri standardı format
          output: "dependency-results.sbom.json"

      # 6. Adım: SBOM Dosyasını Kaydet (Artifact)
      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom-dosyasi # İndirilebilir dosyanın adı
          path: dependency-results.sbom.json

      # 7. Adım: Secret Scan (TruffleHog Kullanımı)
      - name: TruffleHog Secrets Scan
        uses: trufflesecurity/trufflehog@main # Normalde hash ile sabitleriz ama TruffleHog çok sık güncellenir
        with:
          path: ./
          base: main
          head: HEAD
          extra_args: --only-verified # Sadece doğrulanmış (gerçekten çalışan) sırları raporla (Gürültüyü azaltır)
